query GET_POST {
  post(id: "8600") {
    __typename

    ... on Post {
      id
      title
    }

    ... on PostError {
      statusCode
      message

      ... on PostNotFoundError {
        postId
      }

      ... on PostTimeoutError {
        timeout
      }
    }
  }
}
