# QUERY VARIABLES
# {
#   "id": "115",
#   "teste": true
# }
query GET_USERS($id: ID!, $teste: Boolean) {
  user(id: $id, teste: $teste) {
    id
    firstName
    lastName
    userName
    indexRef
    createdAt
  }
}
